'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const C=require('../web/core.js'),D=JSON.parse(fs.readFileSync(path.join(__dirname,'../data.json'),'utf8'));
const reference=()=>C.clean(D,{mode:'reference',chapter:34,phase:'finished'});
test('opening starts in reading mode with only the primary station',()=>{const m=C.model(D,C.defaults());assert.deepEqual(m.nodes.map(n=>n.id),['red-81']);assert.deepEqual(m.groups,['Carl','Donut / Katia']);});
test('beginning chapter excludes same-chapter secondary locations',()=>{const s=C.clean(D,{chapter:14,phase:'beginning'});assert(!C.model(D,s).nodes.some(n=>n.id==='mauve-purple-283'));});
test('finished chapter includes indexed locations without claiming verification',()=>{const s=C.clean(D,{chapter:14,phase:'finished'});assert(C.model(D,s).nodes.some(n=>n.id==='mauve-purple-283'));assert.equal(D.nodes.find(n=>n.id==='mauve-purple-283').tier,'secondary');});
test('future group names are absent from reading choices',()=>{assert(!C.model(D,C.defaults()).groups.includes('Bautista'));});
test('inferred connections are hidden by default',()=>{assert(C.model(D,reference()).edges.every(e=>e.kind!=='sequence'));});
test('explicit guide layer exposes eleven unverified sequences',()=>{assert.equal(C.model(D,{...reference(),inferred:true}).edges.filter(e=>e.kind==='sequence').length,11);});
test('reset clears exploration but preserves reader state and unrelated properties',()=>{const s={...reference(),group:'Bautista',event:'bautista-28-1',query:'83',route:'nightmare',node:'tangerine-plum-83',panel:'detail',inferred:true,notes:{x:'keep'},bookmarks:['keep']};const x=C.reset(s);for(const k of ['chapter','phase','mode','group','event','notes','bookmarks'])assert.deepEqual(x[k],s[k]);for(const k of ['node','route','panel'])assert.equal(x[k],null);assert.equal(x.query,'');assert.equal(x.inferred,false);});
test('83(b) has one stable physical identity',()=>{const r=C.search(D,{...reference(),query:'83(b)'}).results;assert.equal(r.length,1);assert.equal(r[0].id,'tangerine-plum-83');});
test('283 suffixes stay distinct',()=>{for(const [q,id]of [['283(a)','mauve-purple-283'],['283(b)','green-yellow-283']])assert.equal(C.search(D,{...reference(),query:q}).results[0].id,id);});
test('number-only search returns distinct records, not substring matches',()=>{const r=C.search(D,{...reference(),query:'83'}).results;assert.equal(r.length,3);assert(r.every(x=>D.nodes.find(n=>n.id===x.id).number===83));});
test('line plus station number searches globally',()=>{assert(C.search(D,{...reference(),query:'yellow 83'}).results.some(r=>r.id==='red-yellow-83'));});
test('yard query works without selecting a tab',()=>{assert(C.search(D,{...reference(),query:'yard E'}).results.some(r=>r.id==='yard-E'));});
test('mendaro matches canonical Mindaro without changing data',()=>{const r=C.search(D,{...reference(),query:'mendaro'});assert(r.corrected);assert(r.results.some(r=>r.id==='mindaro'));assert(D.routes.some(r=>r.name==='Mindaro'));});
test('fulvis matches Fulvous',()=>{assert(C.search(D,{...reference(),query:'fulvis'}).results.some(r=>r.id==='fulvous'));});
test('future aliases and names do not appear in opening search',()=>{for(const query of ['83(b)','mindaro','Bautista'])assert.equal(C.search(D,{...C.defaults(),query}).results.length,0);});
test('empty query searches all current types',()=>{const r=C.search(D,reference()).results;for(const kind of ['stations','lines','yards','reports'])assert(r.some(x=>x.kind===kind));});
test('new shared links round-trip state',()=>{const s={...reference(),node:'tangerine-plum-83',route:'nightmare',query:'83(b)',inferred:true};const r=C.parse(D,C.hash(s));for(const k of ['chapter','phase','mode','node','route','query','inferred'])assert.equal(r[k],s[k]);});
test('legacy 0.2 links preserve through-chapter and aliases',()=>{const s=C.parse(D,'#v=0.2.0-alpha&ch=14&mode=reading&station=tangerine-plum-83&line=nightmare');assert.equal(s.phase,'finished');assert.equal(s.node,'tangerine-plum-83');});
test('unknown IDs and future selections are discarded',()=>{const s=C.parse(D,'#ch=1&line=nightmare&station=tangerine-plum-83&checkpoint=not-an-event');assert.equal(s.node,null);assert.equal(s.route,null);assert.equal(s.event,'latest');});
test('notes never enter a shared link',()=>{const h=C.hash({...reference(),notes:{a:'SECRET-PRIVATE-NOTE'}});assert(!h.includes('SECRET'));assert(!h.includes('notes'));});
test('checkpoint is chosen from permitted reports only',()=>{const s=C.clean(D,{chapter:5,phase:'finished',event:'carl-34-1'});assert.equal(s.event,'latest');assert(C.model(D,s).report.chapter<=5);});
test('reported reverse movement preserves its direction',()=>{const s=C.clean(D,{chapter:24,phase:'finished',event:'carl-24-1'});const e=C.model(D,s).report;assert.equal(e.travel.from,'vermillion-101');assert.equal(e.travel.to,'vermillion-75');});
test('chapter values are bounded and unknown phases are conservative',()=>{assert.equal(C.clean(D,{chapter:200}).chapter,34);assert.equal(C.clean(D,{chapter:-1}).chapter,1);assert.equal(C.clean(D,{phase:'nonsense'}).phase,'beginning');});
test('new served UI has no duplicate dataset and no inline script',()=>{const html=fs.readFileSync(path.join(__dirname,'../web/reader.html'),'utf8');assert(!html.includes('id="data"'));assert(!/<script[^>]*>\s*[^<\s]/.test(html));});
test('route renderer never creates arrows on general edges',()=>{const js=fs.readFileSync(path.join(__dirname,'../web/reader.js'),'utf8');assert(!js.includes('Where this service goes'));assert.equal((js.match(/marker-end=/g)||[]).length,1);assert(js.includes("edge.kind")||js.includes("x.kind!=='sequence'"));});
test('3D reconstruction is clearly interpretive and not the default',()=>{const html=fs.readFileSync(path.join(__dirname,'../web/reader.html'),'utf8');assert(html.includes('INTERPRETIVE / GEOMETRY UNCONFIRMED'));assert(html.includes('id="noodleView" hidden'));assert(html.includes('opposite faces'));});
test('3D renderer is dependency-free and exposes camera presets',()=>{const js=fs.readFileSync(path.join(__dirname,'../web/noodle3d.js'),'utf8');for(const view of ['top','oblique','side'])assert(js.includes(view));assert(!js.includes('three.js'));assert(js.includes('pointermove'));});
